### ISSUE TITLE
Turn into Template

### ISSUE THREAD

**Issue by rorychatterton** [kinde-starter-kits/nextjs-starter-kit#8]
Can you turn these into templates, so people can copy/create a repository from them more easily? The setting is under the repository settings and looks like:

<img width="716" alt="Screenshot 2023-03-28 at 8 05 20 pm" src="https://user-images.githubusercontent.com/11748379/228186605-0d186805-1b7e-4916-9df5-52e1e7b2de13.png">

It just bypasses the need to download, remove origin, add new origin, reppush to private, etc, and makes it a one-button to clone into a private github org

**Comment by DaveOrDead** [comment]
Great idea - thanks @rorychatterton this is now updated
