### ISSUE TITLE
Extend example to show how AccessToken can be used for downstream API call.

### ISSUE THREAD

**Issue by rorychatterton** [kinde-starter-kits/nextjs-starter-kit#9]
Can this example be extended to show the AccessToken is extracted so that it can be used to call downstream APIs which are not hosted within NextJS itself.

It does not appear that the accessToken is accessible through `useKindeAuth()`

**Comment by DaveOrDead** [comment]
Hey @rorychatterton sorry for the delay.

There is a way but it is a bit convoluted - the NextJS API has a built in endpoint for the token which you could call like so:

```
  const [token, setToken] = useState();

  useEffect(() => {
    (async () => {
      const res = await fetch("/api/auth/get_token");
      const json = await res.json();
      setToken(json);
    })();
  }, []);
```

Obviously, this is not ideal as it requires an additional network request, when actually we already have the token in the frontend. We'll add a method to the SDK to be able to get it more easily - but in the mean time this should work as a temporary solution

**Comment by DaveOrDead** [comment]
Addressed in: https://github.com/kinde-starter-kits/nextjs-starter-kit/pull/10

**Comment by rorychatterton** [comment]
Legend, thanks @DaveOrDead. FYI @thesampaton
